### ISSUE TITLE
Dshot not working properly on 3.5

### ISSUE THREAD

**Issue by holm0208** [ButterFlight/butterflight-configurator#22]
I updated to 3.5, and then my FC only detected one of the tour esc. And when i armed, only one motor would spin. So the FC only had control over one ESC. On multishot, it Works fine. When i uploaded 3.42, All were fine and good again. I use a spracingf3 clone with racerstar rs20a 4in1 ESC.

**Comment by LexioTech** [comment]
@holm0208 Hi, according to your description, this is a Firmware issue, and not a configurator issue  :) Please re-open this at https://github.com/ButterFlight/butterflight/issues

Thank you!

**Comment by Clynikal** [comment]
I encountered this issue. Reflashed ESC’s and it came good.

**Comment by kidBrazil** [comment]
Closing Issue
