### ISSUE TITLE
Can't install on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by Padraignotlad** [ButterFlight/butterflight-configurator#30]
When I try to install 10.4.0 I get an error during installation.  It fails.  So I thought I'd try 10.3.0 and that doesn't give an error, but it won't install either.  Just kind of does nothing.  If you click Install a 2nd time, it will flicker and change to give you the option to remove the software.  But I don't think it actually installs.  I can't find it.  - Padraig

**Comment by kidBrazil** [comment]
@Padraignotlad - For now I would suggest using the Linux 64 Zip and just extracting it somewhere. You can then run it via terminal or create a shortcut for it.

We will be looking into what is broken with deb

**Comment by Padraignotlad** [comment]
Already up and running.  Thanks!

**Comment by kidBrazil** [comment]
This issue apparently was inherited from Betaflight - we are just going to stop supplying Deb packages for now.

**Comment by ghost** [comment]
The issue with ButterFlight on linux is just the name of the file butterflight-configurator.desktop
It is misnamed "betaflight-configurator.desktop" instead of "butterflight-configurator.desktop"
Just rename it and it works.
