### ISSUE TITLE
Avast flags  installer as malware.

### ISSUE THREAD

**Issue by Freakofspeed** [ButterFlight/butterflight-configurator#35]
butterflight-configurator-installer_10.4.1_win64.exe
Was flagged as FileRepMalware by Avast Business Antivirus 18.2.2530
Probably a false positive.

**Comment by kmitchel** [comment]
Quick Google search, and it looks like Avast has a long history of flagging
NSIS installers.

http://nsis.sourceforge.net/NSIS_False_Positives

**Comment by kmitchel** [comment]
I've reported the false positive to Avast.  We'll see if they fix it.

**Comment by kmitchel** [comment]
Avast emailed back. Please update your virus definitions, and try again.  I
wouldn't be surprised if it takes a day or two.

**Comment by Freakofspeed** [comment]
butterflight-configurator-installer_10.4.2_win64.exe
Passed Avast Business Antivirus 18.2.2530 Virus Definions 180425-6

Cheers!
